# Based on https://github.com/mit-plv/fiat-crypto/blob/master/.github/workflows/coq-windows.yml
name: CI (Cygwin/Windows)

on:
  push:
  pull_request:
  workflow_dispatch: {}

jobs:
  build:
    name: cygwin ${{ matrix.CYGWIN_ABI }}bit
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - CYGWIN_ABI: 64
          COVERAGE_FLAG: "--coverage"
          COVERALLS_PARALLEL: "true"
        - CYGWIN_ABI: 32
          COVERAGE_FLAG: ""
          COVERALLS_PARALLEL: "false"

    env:
      CFLAGS:   "${{ matrix.COVERAGE_FLAG }} -O2 -g"
      CXXFLAGS: "${{ matrix.COVERAGE_FLAG }} -O2 -g"
      LDFLAGS:  "${{ matrix.COVERAGE_FLAG }}"
      # default config flags: enable debug asserts
      CONFIGFLAGS: "--enable-debug"
      COVERALLS_PARALLEL: ${{ matrix.COVERALLS_PARALLEL }}
      TEST_SUITES: testinstall

    steps:
    # This sets git to use Linux line endings. While GAP should allow
    # Windows line endings in GAP files, we currently can't build GAP if the
    # whole source has Windows line endings
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v2

    - uses: gap-actions/setup-cygwin-for-gap@test32
      with:
        CYGWIN_ABI: ${{ matrix.CYGWIN_ABI }}

    # CHERE_INVOKING=1 lets us start a 'login shell' (to set paths) without changing directory
    - name: Compile GAP and download packages
      run: |
        @ECHO ON
        SET CHERE_INVOKING=1
        C:\cygwin\bin\bash -l -c 'bash etc/ci-prepare.sh'
      shell: cmd

    - name: Run tests
      run: |
        SET CHERE_INVOKING=1
        C:\cygwin\bin\bash -l -c 'bash etc/ci.sh'
      shell: cmd
